--MOD:d4lilah2
--Copyright d4, 2017--
core = require("d4core")

function Initialize()
	SetMenuLevel(false)
	SetBoundaries(core.Rect(0, 0, 4032, 1728))
	tile = 64
	SpawnEntity('Player', core.Vector(tile * 13, tile * 2))


	SpawnEntity('Cube', core.Vector(tile * 0, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 1, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 2, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 3, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 4, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 5, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 6, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 7, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 8, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 9, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 10, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 11, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 12, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 13, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 14, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 15, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 16, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 17, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 18, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 19, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 20, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	
	SpawnEntity('Cube', core.Vector(tile * 31, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 32, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 33, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 34, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 35, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 36, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 37, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 38, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 39, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 40, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 41, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 42, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 43, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 44, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 45, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 46, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 47, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 48, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 49, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 50, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 51, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 52, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 53, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 54, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 55, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 56, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 57, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 58, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 59, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 60, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 61, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 62, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 63, tile * 15), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })

	SpawnEntity('Cube', core.Vector(tile * 10, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 11, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 12, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 13, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 14, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 15, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 16, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 17, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 18, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 19, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 20, tile * 14), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })

	SpawnEntity('Cube', core.Vector(tile * 17, tile * 13), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 18, tile * 13), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 19, tile * 13), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })
	SpawnEntity('Cube', core.Vector(tile * 20, tile * 13), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })

	SpawnEntity('Cube', core.Vector(tile * 20, tile * 12), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })

	SpawnEntity('Cube', core.Vector(tile * 20, tile * 11), { Texture = 'Sprites/Cube64_12', Direction = core.Direction.Left })

end
--Copyright d4, 2017--